FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    libgles2 \
    libfontconfig1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY spaceships-server.x86_64 .
COPY spaceships-server.pck .

RUN chmod +x spaceships-server.x86_64

EXPOSE 7777
EXPOSE 7778

ENTRYPOINT ["./spaceships-server.x86_64", "--headless"]