version: "3.8"

services:

  rapid-gateway:
    image: localhost/rapid-gateway:latest
    container_name: rapid-gateway
    restart: always
    network_mode: host
    environment:
      - VERSION_JSON_PATH=/config/version.json
    volumes:
      - /home/cecconi/spaceship/relises:/relises
      - /home/cecconi/spaceship:/config:ro

  rapid-server:
    image: localhost/rapid-server:latest
    container_name: rapid-server
    restart: always
    network_mode: host