version: "3.8"

services:

  spaceships-gateway:
    image: localhost/spaceships-gateway:latest
    container_name: spaceships-gateway
    restart: always
    network_mode: host
    environment:
      - VERSION_JSON_PATH=/config/version.json
    volumes:
      - /home/cecconi/spaceships/relises:/relises
      - /home/cecconi/spaceships:/config:ro

  spaceships-server:
    image: localhost/spaceships-server:latest
    container_name: spaceships-server
    restart: always
    network_mode: host
    depends_on:
      - spaceships-gateway